"""Remove base class

Revision ID: 1153df717c9b
Revises: cacbd959e2ee
Create Date: 2024-09-01 23:08:47.375963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1153df717c9b'
down_revision = 'cacbd959e2ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Units_Coordinators_Table',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('unitID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unitID'], ['unit.unitID'], ),
    sa.ForeignKeyConstraint(['userID'], ['user.userID'], ),
    sa.PrimaryKeyConstraint('userID', 'unitID')
    )
    op.create_table('Units_Facilitators_Table',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('unitID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unitID'], ['unit.unitID'], ),
    sa.ForeignKeyConstraint(['userID'], ['user.userID'], ),
    sa.PrimaryKeyConstraint('userID', 'unitID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Units_Facilitators_Table')
    op.drop_table('Units_Coordinators_Table')
    # ### end Alembic commands ###
