"""add user token column

Revision ID: 444150037f4e
Revises: 3bc372b20e9a
Create Date: 2024-10-12 11:19:19.260027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '444150037f4e'
down_revision = '3bc372b20e9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('token')

    # ### end Alembic commands ###
