"""Initial migration.

Revision ID: bd6290023305
Revises: 
Create Date: 2024-08-31 18:20:55.277825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd6290023305'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit',
    sa.Column('unitID', sa.Integer(), nullable=False),
    sa.Column('unitCode', sa.String(length=50), nullable=False),
    sa.Column('unitName', sa.String(length=50), nullable=True),
    sa.Column('studyPeriod', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('startDate', sa.Date(), nullable=False),
    sa.Column('endDate', sa.Date(), nullable=False),
    sa.Column('sessionNames', sa.String(length=2000), nullable=False),
    sa.Column('sessionTimes', sa.String(length=2000), nullable=False),
    sa.Column('comments', sa.Boolean(), nullable=False),
    sa.Column('marks', sa.Boolean(), nullable=False),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('commentSuggestions', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('unitID')
    )
    op.create_table('user',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('uwaID', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=True),
    sa.Column('lastName', sa.String(length=50), nullable=True),
    sa.Column('passwordHash', sa.String(length=256), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('userID'),
    sa.UniqueConstraint('uwaID')
    )
    op.create_table('session',
    sa.Column('sessionID', sa.Integer(), nullable=False),
    sa.Column('unitID', sa.Integer(), nullable=False),
    sa.Column('sessionName', sa.String(length=50), nullable=False),
    sa.Column('sessionTime', sa.String(length=50), nullable=False),
    sa.Column('sessionDate', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['unitID'], ['unit.unitID'], ),
    sa.PrimaryKeyConstraint('sessionID')
    )
    op.create_table('student',
    sa.Column('studentID', sa.Integer(), nullable=False),
    sa.Column('studentNumber', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('preferredName', sa.String(length=50), nullable=False),
    sa.Column('unitID', sa.Integer(), nullable=False),
    sa.Column('consent', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unitID'], ['unit.unitID'], ),
    sa.PrimaryKeyConstraint('studentID')
    )
    op.create_table('attendance',
    sa.Column('attendanceID', sa.Integer(), nullable=False),
    sa.Column('sessionID', sa.Integer(), nullable=False),
    sa.Column('studentID', sa.Integer(), nullable=False),
    sa.Column('signInTime', sa.Time(), nullable=False),
    sa.Column('signOutTime', sa.Time(), nullable=False),
    sa.Column('facilitatorID', sa.Integer(), nullable=False),
    sa.Column('marks', sa.String(length=100), nullable=True),
    sa.Column('comments', sa.String(length=1000), nullable=True),
    sa.Column('consent_given', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['facilitatorID'], ['user.userID'], ),
    sa.ForeignKeyConstraint(['sessionID'], ['session.sessionID'], ),
    sa.ForeignKeyConstraint(['studentID'], ['student.studentID'], ),
    sa.PrimaryKeyConstraint('attendanceID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    op.drop_table('student')
    op.drop_table('session')
    op.drop_table('user')
    op.drop_table('unit')
    # ### end Alembic commands ###
